#!/bin/sh
#
# You probably want to look here first
# https://code.google.com/a/eclipselabs.org/p/workspacemechanic/wiki/GettingStarted
#
# Setup a machine for Eclipse
set -x

# symlink settings in
eclipse_dir=~/.eclipse

mkdir $eclipse_dir

mv "$eclipse_dir/mechanic" "$eclipse_dir/mechanic.backup"
ln -s "$ZSH/eclipse/mechanic" "$eclipse_dir/mechanic"
